# Generated by Django 2.0 on 2018-03-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nullable', models.BooleanField(default=True)),
                ('primary_key', models.BooleanField(default=True)),
                ('business_key', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_name', models.CharField(max_length=200)),
                ('src_col', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='src_col', to='webtool.Column')),
                ('tgt_col', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tgt_col', to='webtool.Column')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='webtool.Schema')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='webtool.Table'),
        ),
    ]
