# Generated by Django 2.0 on 2018-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='select',
            field=models.BooleanField(default=True),
        ),
    ]
