# Generated by Django 2.0 on 2018-03-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='tgt_schema',
            new_name='target_schema',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tgt_table',
            new_name='target_table',
        ),
    ]
