# Generated by Django 2.0 on 2018-03-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtool', '0002_auto_20180303_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='id',
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtool.Schema'),
        ),
    ]
