# Generated by Django 2.0 on 2018-03-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtool', '0004_auto_20180304_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtool.Table'),
        ),
    ]
