# Generated by Django 2.0 on 2018-03-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtool', '0005_auto_20180304_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='webtool.Schema'),
        ),
    ]
